[package]
name = "keep"
version = "0.1.3"
authors = ["Nathan Sizemore <nathanrsizemore@gmail.com>"]

[dependencies]
docopt = "0.8"
lazy_static = "1.0"
pad = "0.1"
serde = "1.0"
serde_derive = "1.0"
sqlite = "0.23"
